### ISSUE TITLE
로그인/회원가입 폼 수정

### ISSUE THREAD

**Issue by gusrb2776** [ApptiveDev/apptive-17th-fruitable-frontend#18]
## 문제/이슈

- [ ] TextField 기존 component로 수정
- [ ] 글자 잘림 및 field 크기 수정
- [ ] 인증 번호 maxlength 수정 및 에러메세지 수정
- [ ] 클래스 이름 시인성 있게 수정
- [ ] 로그인 / 회원가입 State,Event 파일 분리

**Comment by 1jeongg** [comment]
- [ ] focusCleaner 달아서 화면 클릭하면 키보드 사라지도록 처리
- [ ] 인증번호 기간 3분 타이머 기능 구현  -> Coroutine flow사용하시면 됩니다
- [ ] 올바르지 않은 이메일 입력시 안내문구 표시
- [ ] 이용약관 및 개인정보 수집 체크박스 만들기
- [ ] 닉네임 길이 제한에 따른 안내문구 표시
- [ ] 기본정보 입력이 모두 입력되지 않을 시 버튼 문구, 색상 변경
- [ ] 가입 완료 버튼 누를 시 로그인 화면으로 이동
